#!/usr/bin/env bash

# set -x # for debugging

. plumbing

# Assigning Arguments
whichMethod=$1
username="$2"
label_state_or_repo_name=$3
is_private=$4

function fetchIssuesWhereIAmAssignedWithLabel {
  response=$(github_get search/issues?q=+label:${label_state_or_repo_name}+assignee:${username}+state:open&sort=created&order=asc)
  echo "$response"
}

function fetchNotificationsByRepo {
  response=$(github_get repos/${username}/${label_state_or_repo_name}/notifications)
  echo "$response"
}

function fetchRepoComments {
  response=$(github_get repos/${username}/${label_state_or_repo_name}/comments)
  echo "$response"
}

function createNewRepo {
  body="{\"name\":\"${label_state_or_repo_name}\",\"description\":\"$username\",\"private\":${is_private},\"has_issues\":true,\"has_wiki\":true,\"has_downloads\":false}"
  response=$(github_post user/repos ${body})
  echo "$response"
}

# Determining Which Method To Call Based On Command Line Arguments
if [ $whichMethod == "assigned"  ]
  then fetchIssuesWhereIAmAssignedWithLabel
elif [ $whichMethod == "notifications" ]
  then fetchNotificationsByRepo
elif [ $whichMethod == "comments" ]
  then fetchRepoComments
elif [ $whichMethod == "new_repo" ]
  then createNewRepo
else
  echo invalid method name
fi
