#!/usr/bin/env bash
# TODO standardize format
# set -x # for debugging

. plumbing

#### CORE FUNCTIONS
# TODO replace with plumbing

gh_request()
{
  local gh_request_route=$@
  if [ -n "$GH_TOKEN" ]
  then
    curl -s -G "https://api.github.com/$gh_request_route" -H "User-Agent: nathos/ghinfo" -H "Accept: application/vnd.github.full+json" -H "Authorization: token $GH_TOKEN"
  else
    curl -s -G "https://api.github.com/$gh_request_route" -H "User-Agent: nathos/ghinfo" -H "Accept: application/vnd.github.full+json"
  fi
}

api_request()
{
  local api_request_result=$( gh_request "$1") # only make a single API request
  shift # Shift 

  api_request_filtered=() # initialize/empty filtered results array

  # loop through all requested jq filter arguments
  for arg in $* ; do
    _response=$( echo $api_request_result | jq -r "$arg" )
    if [[ -n $_response ]] ; then
      api_request_filtered+=("$_response") # append to filtered result array
    # else
    #   echo "No response for $arg"
    fi
  done
}

api_request_forks() # FIXME: refactor this into the main api_request function
{
  local api_request_result=$( gh_request "$1") # only make a single API request

  api_request_filtered=() # initialize/empty filtered results array

  response=$( echo $api_request_result | jq -r '.[] | .owner.login' )
}


#### COLORS & FORMATTING

_red=$(tput setaf 1)
_green=$(tput setaf 2)
_yellow=$(tput setaf 3)
_blue=$(tput setaf 4)
_magenta=$(tput setaf 5)
_cyan=$(tput setaf 6)
_white=$(tput setaf 7)

_bold=$(tput bold)

_reset=$(tput sgr0)

_error=${_red}${_bold}
_command=${_yellow}${_bold}
_target=${_magenta}
_em=${_blue}${_bold}


##### META 

dependency_test()
{
  for dep in curl jq ; do
    command -v $dep &>/dev/null || { echo -e "\n${_error}Error:${_reset} I require the ${_command}$dep${_reset} command but it's not installed.\n"; exit 1; }
  done
}

usage()
{
  echo -e "Usage: $0 [options] <argv>...\n"
  echo "Options:"
  echo " -f | --forks <user/repository>   Display fork details"
  echo " -r | --repo  <user/repository>   Display repo details"
  echo " -u | --user  <username>          Display user details"
  echo " -t | --token <token>             Set a GitHub token"
  echo " -h | --help                      Help"
  echo ""
}


#### HELPERS - to reduce duplication

set_user_context()
{
  context=$(echo "$1" | sed -e 's/^https*:\/*//' -e 's/github\.com\/*//' -e 's#/$## ')
}

set_repo_context()
{
  context=$(echo "$1" | sed -e 's/^https*:\/*//' -e 's/github\.com\/*//' -e 's/\.*git$//' -e 's#/$##')
}

print_whitespace()
{
  for i in $(seq 1 $1); do
      echo -n " "
  done
}

print_header()
{
  local name_length=${#context}
  local header_length=$(( name_length + 13 ))
  
  echo -e "\nDetails for ${_target}$context${_reset}:"
  for i in $(seq 1 $header_length); do
    echo -n "="
  done
  echo -e "\n"
}


#### FORMATTED REQUEST FUNCTIONS
#    Uses format: `api_request 'API_ROUTE' 'FILTER1' 'FILTER2' ...`

user_details()
{
  print_header 
  api_request "users/$context" '.name' '.location' '.email' '.bio' '.public_repos' '.public_gists' '.followers' '.following' '.created_at'

  local name_length=${#context}

  local name=${api_request_filtered[0]}
  local location=${api_request_filtered[1]}
  local email=${api_request_filtered[2]}
  local bio=${api_request_filtered[3]}
  local public_repos=${api_request_filtered[4]}
  local public_gists=${api_request_filtered[5]}
  local followers=${api_request_filtered[6]}
  local following=${api_request_filtered[7]}
  local user_since=${api_request_filtered[8]}

  echo "     Name: $name"
  echo " Location: $location"

  if [ $email != "null" ]; then
    echo "    Email: $email"
  fi

  if [ "$bio" != "null" ]; then
    echo "      Bio: $bio"
  fi

  echo -e "\n ${_magenta}$context${_reset} has shared ${_em}$public_repos${_reset} public git repositories and ${_em}$public_gists${_reset} gists.\n"
  print_whitespace $name_length

  echo -e "  is followed by ${_em}$followers${_reset} GitHub users and follows ${_em}$following${_reset} users.\n"
  print_whitespace $name_length

  echo -e "  has been a happy GitHub user since ${_em}${user_since:0:10}${_reset}."
}

repo_details()
{
  print_header 
  api_request "repos/$context" '.name' '.owner.login' '.description' '.forks_count' '.stargazers_count' '.open_issues_count' '.created_at' '.updated_at' '.parent.name' '.parent.owner.login' '.clone_url' '.homepage'

  local name_length=${#context}
  local name=${api_request_filtered[0]}
  local owner=${api_request_filtered[1]}
  local description=${api_request_filtered[2]}
  local forks_count=${api_request_filtered[3]}
  local stargazers_count=${api_request_filtered[4]}
  local open_issues_count=${api_request_filtered[5]}
  local created_at=${api_request_filtered[6]}
  local updated_at=${api_request_filtered[7]}
  local parent_name=${api_request_filtered[8]}
  local parent_owner=${api_request_filtered[9]}
  local clone_url=${api_request_filtered[10]}
  local homepage=${api_request_filtered[11]}

  echo -e " ${_bold}${_white}$name${_reset} by $owner\n"
  
  if [ "$description" != "null" ]; then
    echo " $description" | fmt
  fi

  if [ "$homepage" != "null" ]; then
    echo " Homepage: $homepage"
  fi

  echo -e "\n ${_target}$context${_reset} has been forked ${_em}$forks_count${_reset} times and starred ${_em}$stargazers_count${_reset} times.\n"
  print_whitespace $name_length

  echo -e "  has ${_em}$open_issues_count${_reset} open issues.\n"
  print_whitespace $name_length

  echo -e "  was created on ${_em}${created_at:0:10}${_reset} and last updated on ${_em}${updated_at:0:10}${_reset}."

  if [ $parent_name != "null" ]; then
    echo -e "\n\n ${_target}$name${_reset} was forked from ${_yellow}$parent_name${_yellow} by ${_yellow}$parent_owner${_reset}"
  fi

  echo -e "\n Clone URL: $clone_url \n"
}

list_forks()
{
  print_header 
  api_request "repos/$context" '.name' '.owner.login' '.forks_count'

  echo -e "${_bold}${_white}${api_request_filtered[0]}${_reset} by ${api_request_filtered[1]}\n"
  echo -e "\n${_target}$context${_reset} has been forked ${_em}${api_request_filtered[2]}${_reset} times, including forks by these GitHub users:\n"
  api_request_forks "repos/$context/forks"
  echo -e "${_blue}$response${_reset}"
  echo ""
}


#### MAIN

dependency_test

# Print help if no params are passed.
if [ -z $1 ]; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
  case $1 in
    -h | --help )   usage
                    exit ;;
    -t | --token )  shift
                    GH_TOKEN="$1" ;;
    -u | --user )   shift
                    set_user_context "$1"
                    user_details ;;
    -r | --repo )   shift
                    set_repo_context "$1"
                    repo_details ;;
    -f | --forks )  shift
                    set_repo_context "$1"
                    list_forks
                    exit ;;
    * )             usage
                    exit 1
  esac
  shift
done
