#!/usr/bin/env bash
#
# Print the number of deleted files per directory. The output indicates
# if the directory is present in the HEAD revision.
#
# A deleted directory with a lot of files could indicate a 3rd party
# component that has been deleted. These are usually good candidates for
# purging to make Git repositories smaller (see `git-purge-files`).
#
# The script must be called from the root of the Git repository.
#
# Usage:
# git-find-dirs-deleted-files
#
# Output: [deleted file count] [directory still in HEAD revision?] [directory]
#
# Author: Lars Schneider, https://github.com/larsxschneider
#

git -c diff.renameLimit=30000 log --diff-filter=D --summary |
    grep ' delete mode ...... ' |
    sed 's/ delete mode ...... //' |
    while read -r F ; do
        D=$(dirname "$F");
        if ! [ -d "$D" ]; then
            while ! [ -d "$(dirname "$D")" ] ; do D=$(dirname "$D"); done;
            echo "deleted $D";
        else
            echo "present $D";
        fi;
    done |
    sort |
    uniq -c |
    sort -k 2,2 -r
